[settings]
base_url = "https://api.cantex.io"
execution_mode = "sequential"
max_concurrency = 1
swap_delay_seconds = { min = 10.0, max = 30.0 }
max_network_fee_cc_per_execution = "0.12"
network_fee_poll_seconds = { min = 20.0, max = 40.0 }
full_24h_mode = true
full_24h_startup_mode = "planned"
full_24h_min_gap_minutes = 5
full_24h_auto_restart = true
weekly_stop_on_monday_utc = true
full_24h_schedule_log_limit = 12
random_seed = ""
telegram_enabled = true
telegram_bot_token = "env:TELEGRAM_BOT_TOKEN"
telegram_chat_id = "env:TELEGRAM_CHAT_ID"
terminal_dashboard_enabled = true
terminal_dashboard_logs_limit = 20
terminal_dashboard_min_interval_seconds = 0.25
telegram_update_min_interval_seconds = 5
telegram_latest_logs_limit = 6
activity_enabled = false
activity_items_limit = 5
dry_run = false
log_level = "INFO"
default_continue_on_low_balance = true
max_retries = 3
retry_base_delay = 5.0

[defaults]
strategy = "3"
rounds = { min = 70, max = 72 }
amounts = { CC = { min = "11", max = "13" }, USDCx = { min = "1.5", max = "1.7" }, CBTC = { min = "0.000023", max = "0.000025" } }
reserve_fee = "5"
# reserve_kritis = "1"

[[accounts]]
name = "wallet-1"
enabled = true
operator_key = "env:CANTEX_OPERATOR_KEY_1"
trading_key = "env:CANTEX_TRADING_KEY_1"
proxy_label = "No proxy"
allow_continue_on_low_balance = true
auto_create_intent_account = true

[[accounts]]
name = "wallet-2"
enabled = true
operator_key = "env:CANTEX_OPERATOR_KEY_2"
trading_key = "env:CANTEX_TRADING_KEY_2"
proxy_label = "No proxy"
allow_continue_on_low_balance = true
auto_create_intent_account = true

[[accounts]]
name = "wallet-3"
enabled = false
operator_key = "env:CANTEX_OPERATOR_KEY_3"
trading_key = "env:CANTEX_TRADING_KEY_3"
proxy_label = "No proxy"
strategy = "4"
rounds = { min = 6, max = 9 }
reserve_fee = "5"
reserve_kritis = "1"
allow_continue_on_low_balance = true
auto_create_intent_account = true
